Added event listener
VadimGarkusha/nanoleaf-client pull request #10
Opened 2020-11-19 06:13 UTC by BullFrog13

2020-11-20 02:52 UTC, VadimGarkusha requested changes

2020-11-20 02:52 UTC, VadimGarkusha commented on src/event-listener.js
> +  subscribe(events, callback) {
I suggest documenting parameters with a short method explanation here

2020-11-20 02:59 UTC, BullFrog13 commented on src/event-listener.js
> +  subscribe(events, callback) {
Makes sense

2020-11-21 18:03 UTC, VadimGarkusha approved these changes

2020-11-21 21:18 UTC, merged